name: Deploy to Dev Server

on:
  push:
    branches:
      - main
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm i --legacy-peer-deps && npm install apexcharts --legacy-peer-deps
      - name: Build with Next.js
        run:  npm run build

      - name: Restore build cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: .next/cache
          key: nextjs-build-${{ github.sha }}
          restore-keys: |
            nextjs-build-

      - name: Save build cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: nextjs-build-${{ github.sha }}

      - name: Save build cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: nextjs-build-${{ github.sha }}


      - name: Archive production build
        run: |
          zip -r nextjs-build.zip .next package.json package-lock.json public
  

      - name: Copy ZIP to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "nextjs-build.zip"
          target: "/home/deploy/pharmy-landing-page/"


      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/pharmy-landing-page
            unzip -o nextjs-build.zip
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i --legacy-peer-deps
            pm2 restart pharmy-landing-page || pm2 start npm --name "pharmy-landing-page" -- start
            rm nextjs-build.zip
